
sudo: required
services:
  - docker

before_install:
  - docker build -t jdezotel/docker-react-app -f Dockerfile.dev .

script:
  - docker run jdezotel/docker-react-app npm test --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "Docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-525182015898"
  bucket_path: "Docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"